### ISSUE TITLE
Little help for the beginner

### ISSUE THREAD

**Issue by vlatkoB** [justinwoo/spacchetti-react-basic-starter#4]
Hi, 
a day old purescript beginner here.
I cloned the repo, run ```spago upgrade-set```, ```spago install```, ```spago build``` and then tried both
 ```
$ spago run
```
getting this error (full path replaced with '...'): 
```
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '.../spacchetti-react-basic-starter'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
and (as suggested in `spago` readthedocs)

```
$ spago bundle-app --main Main --to index.js
$ node .
```
getting this error:
```
.../spacchetti-react-basic-starter/index.js:750
    return window;
    ^

ReferenceError: window is not defined
    at exports.window (.../spacchetti-react-basic-starter/index.js:750:5)
    at .../spacchetti-react-basic-starter/index.js:269:18
    at .../spacchetti-react-basic-starter/index.js:269:18
    at .../spacchetti-react-basic-starter/index.js:269:22
    at .../spacchetti-react-basic-starter/index.js:269:18
    at Object.__do [as main] (.../spacchetti-react-basic-starter/index.js:804:285)
    at Object.<anonymous> (.../spacchetti-react-basic-starter/index.js:815:12)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
```
I'm on Arch, using ```node v12.10.0```, ```npm 6.11.3```, ```spago 0.9.0.0``` and package set upgraded to ```psc-0.13.3-20190831``` (there were errors even with the original package set).

Is it something in my environment, in newer node/npm or am I trying to run it the wrong way?

**Comment by vlatkoB** [comment]
If any other newby stumbles upon the same issue, I managed to get it to work by actually using its `make` which I missed focusing too much on various tutorials. 
So, `make npm-deps`, `make parcell-build` and `make start`. For hot reloading open two terminals, in first `spago build -w`, in the other one  `parcel watch src/index.html`.
